version: '3'
services:
  z-cli-mongo:
    image: mongo
    container_name: z-cli-mongo
    volumes:
      - '.docker-volumes/mongo/data:/data/db'
      - './mongo-entrypoint:/docker-entrypoint-initdb.d/'
    ports:
      - 27018:27017
    env_file:
      - .env
  z-cli-redis:
    image: redis
    container_name: z-cli-redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - 6380:6379
    env_file:
      - .env
  z-cli-api:
    depends_on:
      - z-cli-mongo
      - z-cli-redis
    image: registry.cn-hangzhou.aliyuncs.com/hapinesszj/z-cli-api:{{tag}}
    container_name: z-cli-api
    ports:
     - 7002:7001
    env_file:
      - .env